# 多阶段构建
FROM node:20-alpine AS builder
RUN apk add --no-cache python3 make g++
RUN npm config set registry https://registry.npmmirror.com/  && \
    npm cache clean --force
WORKDIR /app
COPY package.json ./
RUN npm install --production --legacy-peer-deps

FROM node:20-alpine
RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    font-noto-cjk

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules


COPY package.json ./
COPY index.js ./

# 最终命令：启动 cron 并给 shell
CMD ["crond", "-f", "-l", "4"]

