# 多阶段构建
FROM node:20-alpine AS builder
RUN apk add --no-cache python3 make g++
WORKDIR /app
COPY package.json ./
# npm 配置（加速 + 清理）
RUN npm config set registry https://registry.npmmirror.com/ 
RUN npm install --production --legacy-peer-deps

FROM node:20-alpine
RUN apk add --no-cache \
    chromium nss freetype harfbuzz ca-certificates ttf-freefont font-noto-cjk \
    openssh-client sshpass curl

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules

RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh

# 复制私钥
COPY id_cron /root/.ssh/id_cron
RUN chmod 600 /root/.ssh/id_cron && \
    echo "Host *" >> /root/.ssh/config && \
    echo "  StrictHostKeyChecking no" >> /root/.ssh/config && \
    echo "  IdentityFile /root/.ssh/id_cron" >> /root/.ssh/config

COPY package.json ./
COPY index.js ./

# 最终命令：启动 cron 并给 shell
CMD ["crond", "-f", "-l", "4"]

