name: Test Docker image

on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: pulldocker
        run: |
          docker pull ghcr.io/mydocker-repo/node-puppeteer:custom-25.11.25
          docker images
          docker run --name puppeteer -v $(pwd)/data:/data ghcr.io/mydocker-repo/node-puppeteer:custom-25.11.25 sh -c "node /app/index.js&&ls -l &&cp *.png /data"

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: 自动更新文件"
