name: Test Docker image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: pulldocker
        run: |
          docker pull ghcr.io/mydocker-repo/node-puppeteer:custom-25.11.25
          docker -it node-puppeteer bash
          
